FROM microsoft/dotnet:2.1-sdk-stretch-arm32v7

ENV VSTS_POOL=default VSTS_AGENT=myAgent VSTS_AGENT_VERSION=2.147.1

# Install curl, wget and git
RUN apt-get update && apt-get install -y \
curl \
wget \
git
 
# Download compiles vsts-agent
RUN curl https://vstsagentpackage.azureedge.net/agent/$VSTS_AGENT_VERSION/vsts-agent-linux-arm-$VSTS_AGENT_VERSION.tar.gz -o vsts-agent.tar.gz
RUN mkdir myagent
RUN tar xzf vsts-agent.tar.gz -C ./myagent
 
# install node
RUN curl -sL https://deb.nodesource.com/setup_8.x
RUN apt-get install -y nodejs

COPY vsts.sh .

ENTRYPOINT [ "/bin/bash", "./vsts.sh" ]

